from pydantic import BaseModel, Field
from typing import Optional

class CompanyShort(BaseModel):
    company_id: Optional[int] = Field(default=None, description="Sample: 1")
    name: Optional[str] = Field(default=None, description="Sample: Accenture plc")
    short_name: Optional[str] = Field(default=None, description="Sample: Accenture")
    logo_url: Optional[str] = Field(default=None, description="Sample: https://www.accenture.com/_acnmedia/Accenture/Dev/RedesigNAcc_Logo_Black.svg")
    category: Optional[str] = Field(default=None, description="Sample: Enterprise")
    operating_countries: Optional[str] = Field(default=None, description="Sample: United States; United Kingdom; India; Germany; France; Japan; Australia; Canada; Brazil; Singapore")
    office_locations: Optional[str] = Field(default=None, description="Sample: New York, United States; London, United Kingdom; Bangalore, India; Paris, France; Tokyo, Japan; Toronto, Canada; Sydney, Australia; Frankfurt, Germany")
    employee_size: Optional[str] = Field(default=None, description="Sample: 740,000 employees")
    yoy_growth_rate: Optional[str] = Field(default=None, description="Sample: 3%")

class CompanyFull(BaseModel):
    company_id: Optional[int] = Field(default=None, description="Sample: 1")
    name: Optional[str] = Field(default=None, description="Sample: Accenture plc")
    short_name: Optional[str] = Field(default=None, description="Sample: Accenture")
    logo_url: Optional[str] = Field(default=None, description="Sample: https://www.accenture.com/_acnmedia/Accenture/Dev/RedesigNAcc_Logo_Black.svg")
    category: Optional[str] = Field(default=None, description="Sample: Enterprise")
    incorporation_year: Optional[int] = Field(default=None, description="Sample: 1989")
    overview_text: Optional[str] = Field(default=None, description="Sample: Accenture is a global professional services company providing strategy, consulting, digital, technology, and operations services, serving large enterprises and governments across more than 120 countries with a strong focus on cloud, AI, and digital transformation.")
    nature_of_company: Optional[str] = Field(default=None, description="Sample: Public")
    headquarters_address: Optional[str] = Field(default=None, description="Sample: Dublin, Ireland")
    operating_countries: Optional[str] = Field(default=None, description="Sample: United States; United Kingdom; India; Germany; France; Japan; Australia; Canada; Brazil; Singapore")
    office_count: Optional[str] = Field(default=None, description="Sample: 200+")
    office_locations: Optional[str] = Field(default=None, description="Sample: New York, United States; London, United Kingdom; Bangalore, India; Paris, France; Tokyo, Japan; Toronto, Canada; Sydney, Australia; Frankfurt, Germany")
    employee_size: Optional[str] = Field(default=None, description="Sample: 740,000 employees")
    hiring_velocity: Optional[str] = Field(default=None, description="Sample: Technology ~15,000 open roles; Consulting ~8,000 open roles; Operations ~6,000 open roles; Sales ~2,000 open roles")
    employee_turnover: Optional[str] = Field(default=None, description="Sample: 15% annually (industry benchmark estimate)")
    avg_retention_tenure: Optional[str] = Field(default=None, description="Sample: 4.5 years")
    pain_points_addressed: Optional[str] = Field(default=None, description="Sample: Digital transformation complexity; Legacy IT modernization; Cloud migration risk; Talent and skill gaps; Cybersecurity threats; Operational inefficiency")
    focus_sectors: Optional[str] = Field(default=None, description="Sample: Financials; Health Care; Consumer Discretionary; Industrials; Energy; Telecommunications; Public Sector; Technology")
    offerings_description: Optional[str] = Field(default=None, description="Sample: Management Consulting; Technology Services; Cloud Solutions; AI & Analytics; Cybersecurity; Business Process Outsourcing; Digital Engineering")
    top_customers: Optional[str] = Field(default=None, description="Sample: Fortune 500 Enterprises; Global Banks; Government Agencies; Healthcare Systems; Telecom Operators; Energy Majors")
    core_value_proposition: Optional[str] = Field(default=None, description="Sample: End-to-end transformation; Global delivery scale; Deep industry expertise; Strong technology partnerships; Innovation leadership")
    vision_statement: Optional[str] = Field(default=None, description="Sample: To drive continuous innovation and help the worldâs leading organizations build their digital core and achieve greater value.")
    mission_statement: Optional[str] = Field(default=None, description="Sample: Deliver on the promise of technology and human ingenuity to create value and shared success for clients, people, shareholders, partners, and communities.")
    core_values: Optional[str] = Field(default=None, description="Sample: Client value creation; Integrity; Respect for individuals; Innovation; Stewardship; Best people")
    unique_differentiators: Optional[str] = Field(default=None, description="Sample: Global delivery network; Industry-specific consulting; Strong alliance ecosystem; Proprietary AI and analytics platforms")
    competitive_advantages: Optional[str] = Field(default=None, description="Sample: Brand leadership; Scale and geographic reach; Deep enterprise relationships; Strong partner network")
    weaknesses_gaps: Optional[str] = Field(default=None, description="Sample: High cost structure; Dependency on large enterprise spending cycles; Complex organizational structure")
    key_challenges_needs: Optional[str] = Field(default=None, description="Sample: Talent retention; Pricing pressure from competitors; Rapid AI disruption; Regulatory compliance across regions")
    key_competitors: Optional[str] = Field(default=None, description="Sample: IBM Consulting; Deloitte; TCS; Infosys; Capgemini; Cognizant; Wipro; PwC; EY")
    technology_partners: Optional[str] = Field(default=None, description="Sample: Microsoft; SAP; Oracle; AWS; Google Cloud; Salesforce; NVIDIA")
    history_timeline: Optional[str] = Field(default=None, description="Sample: One of the largest employers of tech talent globally; Invests over $1B annually in R&D and innovation")
    recent_news: Optional[str] = Field(default=None, description="Sample: 2024,Invested $3B in generative AI strategy; 2024,Acquired multiple cloud and AI consulting firms in Europe")
    website_url: Optional[str] = Field(default=None, description="Sample: https://www.accenture.com")
    website_quality: Optional[str] = Field(default=None, description="Sample: Enterprise-grade, high clarity, strong thought leadership, polished UX")
    website_rating: Optional[str] = Field(default=None, description="Sample: NA")
    website_traffic_rank: Optional[str] = Field(default=None, description="Sample: Global 12,000; US 4,000 ")
    social_media_followers: Optional[int] = Field(default=None, description="Sample: 15000000")
    glassdoor_rating: Optional[float] = Field(default=None, description="Sample: 38443.00011574074")
    indeed_rating: Optional[float] = Field(default=None, description="Sample: 38444.00011574074")
    google_rating: Optional[float] = Field(default=None, description="Sample: 38445.00011574074")
    linkedin_url: Optional[str] = Field(default=None, description="Sample: https://www.linkedin.com/company/accenture")
    twitter_handle: Optional[str] = Field(default=None, description="Sample: @Accenture")
    facebook_url: Optional[str] = Field(default=None, description="Sample: https://www.facebook.com/accenture")
    instagram_url: Optional[str] = Field(default=None, description="Sample: https://www.instagram.com/accenture")
    ceo_name: Optional[str] = Field(default=None, description="Sample: Julie Sweet")
    ceo_linkedin_url: Optional[str] = Field(default=None, description="Sample: https://www.linkedin.com/in/juliesweet")
    key_leaders: Optional[str] = Field(default=None, description="Sample: Julie Sweet,Chair & CEO;Manish Sharma,CEO; Jack Azagury,Group Chief Executive")
    warm_intro_pathways: Optional[str] = Field(default=None, description="Sample: Fortune 500 board connections; Alumni network; Technology partner ecosystems")
    decision_maker_access: Optional[str] = Field(default=None, description="Sample: Low,Large enterprise structure with formal procurement and partner-led access")
    primary_contact_email: Optional[str] = Field(default=None, description="Sample: contact@accenture.com")
    primary_phone_number: Optional[str] = Field(default=None, description="Sample: NA")
    contact_person_name: Optional[str] = Field(default=None, description="Sample: Julie Sweet")
    contact_person_title: Optional[str] = Field(default=None, description="Sample: CEO")
    contact_person_email: Optional[str] = Field(default=None, description="Sample: prabhakar.d.phatak@accenture.com")
    contact_person_phone: Optional[str] = Field(default=None, description="Sample: 793 1578")
    awards_recognitions: Optional[str] = Field(default=None, description="Sample: Fortune Global 500; Great Place to Work Certified; Gartner Magic Quadrant Leader; Forbes Most Admired Companies")
    brand_sentiment_score: Optional[str] = Field(default=None, description="Sample: Very Positive,strong global brand, high enterprise trust")
    event_participation: Optional[str] = Field(default=None, description="Sample: World Economic Forum; Microsoft Ignite; AWS re:Invent; Global Fintech Fest")
    regulatory_status: Optional[str] = Field(default=None, description="Sample: ISO 27001; SOC 2; GDPR Compliance; HIPAA Compliance")
    legal_issues: Optional[str] = Field(default=None, description="Sample: Periodic labor and contract disputes; no major unresolved global litigation")
    annual_revenue: Optional[str] = Field(default=None, description="Sample: $64.1B (FY2024)")
    annual_profit: Optional[str] = Field(default=None, description="Sample: $7.2B net income (FY2024)")
    revenue_mix: Optional[str] = Field(default=None, description="Sample: Consulting 55%;ManagedServices 45%")
    valuation: Optional[str] = Field(default=None, description="Sample: $220B market capitalization ")
    yoy_growth_rate: Optional[float] = Field(default=None, description="Sample: 0.03")
    profitability_status: Optional[str] = Field(default=None, description="Sample: Profitable")
    market_share_percentage: Optional[str] = Field(default=None, description="Sample: 6â7% of global IT services market")
    key_investors: Optional[str] = Field(default=None, description="Sample: Vanguard Group; BlackRock; State Street")
    recent_funding_rounds: Optional[str] = Field(default=None, description="Sample: Public equity markets,ongoing institutional investment")
    total_capital_raised: Optional[str] = Field(default=None, description="Sample: Public market funded")
    esg_ratings: Optional[str] = Field(default=None, description="Sample: Net-zero commitment by 2025; Science Based Targets; Diversity equity programs")
    sales_motion: Optional[str] = Field(default=None, description="Sample: Enterprise Field Sales")
    customer_acquisition_cost: Optional[str] = Field(default=None, description="Sample: $100K+ per enterprise ")
    customer_lifetime_value: Optional[str] = Field(default=None, description="Sample: $5M+")
    cac_ltv_ratio: Optional[str] = Field(default=None, description="Sample: NA")
    churn_rate: Optional[str] = Field(default=None, description="Sample: <3%")
    net_promoter_score: Optional[int] = Field(default=None, description="Sample: 60")
    customer_concentration_risk: Optional[str] = Field(default=None, description="Sample: No,highly diversified client base")
    burn_rate: Optional[str] = Field(default=None, description="Sample: Not Applicable,cash-flow positive")
    runway_months: Optional[str] = Field(default=None, description="Sample: Not Applicable")
    burn_multiplier: Optional[str] = Field(default=None, description="Sample: <1.0")
    intellectual_property: Optional[str] = Field(default=None, description="Sample: Accenture Labs IP; Industry AI frameworks; Proprietary cloud accelerators")
    r_and_d_investment: Optional[str] = Field(default=None, description="Sample: $1.5B annually")
    ai_ml_adoption_level: Optional[str] = Field(default=None, description="Sample: High,generative AI platforms, AI-led consulting, automation for delivery optimization")
    tech_stack: Optional[str] = Field(default=None, description="Sample: SAP; Salesforce; AWS; Microsoft Azure; ServiceNow; Kubernetes; Python")
    cybersecurity_posture: Optional[str] = Field(default=None, description="Sample: ISO 27001; SOC 2; Global cyber defense centers")
    supply_chain_dependencies: Optional[str] = Field(default=None, description="Sample: Cloud providers; Software vendors; Talent workforce")
    geopolitical_risks: Optional[str] = Field(default=None, description="Sample: Trade regulations; Data privacy laws; Regional conflicts")
    macro_risks: Optional[str] = Field(default=None, description="Sample: Global recession; Enterprise IT budget cuts")
    diversity_metrics: Optional[str] = Field(default=None, description="Sample: 47% women workforce; Global DEI programs")
    remote_policy_details: Optional[str] = Field(default=None, description="Sample: Hybrid, 60% flexible")
    training_spend: Optional[str] = Field(default=None, description="Sample: $1,500 per employee/year")
    partnership_ecosystem: Optional[str] = Field(default=None, description="Sample: Microsoft; SAP; Oracle; Google; AWS; Salesforce")
    exit_strategy_history: Optional[str] = Field(default=None, description="Sample: Mature public enterprise; Strategic acquisitions")
    carbon_footprint: Optional[str] = Field(default=None, description="Sample: Actively reducing via renewable energy sourcing")
    ethical_sourcing: Optional[str] = Field(default=None, description="Sample: Supplier code of conduct; ESG audits")
    benchmark_vs_peers: Optional[str] = Field(default=None, description="Sample: Higher revenue than Capgemini; Comparable margins to IBM Consulting; Stronger cloud alliances than TCS")
    future_projections: Optional[str] = Field(default=None, description="Sample: Revenue projected $70B by 2027")
    strategic_priorities: Optional[str] = Field(default=None, description="Sample: Generative AI leadership; Cloud transformation; Sustainability consulting; Emerging markets growth")
    industry_associations: Optional[str] = Field(default=None, description="Sample: World Economic Forum; NASSCOM; Business Roundtable")
    case_studies: Optional[str] = Field(default=None, description="Sample: Microsoft cloud modernization; Unilever digital supply chain")
    go_to_market_strategy: Optional[str] = Field(default=None, description="Sample: Enterprise account teams; Strategic alliances; Thought leadership marketing")
    innovation_roadmap: Optional[str] = Field(default=None, description="Sample: GenAI platforms; Industry cloud solutions; Cyber resilience tools")
    product_pipeline: Optional[str] = Field(default=None, description="Sample: AI copilots; Industry SaaS accelerators")
    board_members: Optional[str] = Field(default=None, description="Sample: Julie Sweet; David Rowland; Former global executives")
    marketing_video_url: Optional[str] = Field(default=None, description="Sample: https://www.youtube.com/@Accenture")
    customer_testimonials: Optional[str] = Field(default=None, description="Sample: Unilever transformation story; Microsoft cloud case")
    tech_adoption_rating: Optional[str] = Field(default=None, description="Sample: High,Industry Leader; Top-tier among peers")
    tam: Optional[str] = Field(default=None, description="Sample: $1.5T global IT and business services")
    sam: Optional[str] = Field(default=None, description="Sample: $400B enterprise digital transformation")
    som: Optional[float] = Field(default=None, description="Sample: 0.07")
    work_culture_summary: Optional[str] = Field(default=None, description="Sample: Collaborative; Performance-driven")
    manager_quality: Optional[str] = Field(default=None, description="Sample: Strong coaching focus")
    psychological_safety: Optional[str] = Field(default=None, description="Sample: High")
    feedback_culture: Optional[str] = Field(default=None, description="Sample: Continuous feedback; Annual reviews")
    diversity_inclusion_score: Optional[str] = Field(default=None, description="Sample: Gender equity; Inclusive leadership")
    ethical_standards: Optional[str] = Field(default=None, description="Sample: High integrity; Compliance-driven")
    typical_hours: Optional[str] = Field(default=None, description="Sample: Flexible")
    overtime_expectations: Optional[str] = Field(default=None, description="Sample: Occasional during project peaks")
    weekend_work: Optional[str] = Field(default=None, description="Sample: Rare")
    flexibility_level: Optional[str] = Field(default=None, description="Sample: Remote; Hybrid")
    leave_policy: Optional[str] = Field(default=None, description="Sample: Paid leave; Mental health days")
    burnout_risk: Optional[str] = Field(default=None, description="Sample: Moderate")
    location_centrality: Optional[str] = Field(default=None, description="Sample: Central business districts")
    public_transport_access: Optional[str] = Field(default=None, description="Sample: Metro; Bus; Train")
    cab_policy: Optional[str] = Field(default=None, description="Sample: Ride-hailing; Company transport")
    airport_commute_time: Optional[str] = Field(default=None, description="Sample: 45 minutes")
    office_zone_type: Optional[str] = Field(default=None, description="Sample: IT hub")
    area_safety: Optional[str] = Field(default=None, description="Sample: Secure; Well-monitored")
    safety_policies: Optional[str] = Field(default=None, description="Sample: Late-night transport; Workplace safety")
    infrastructure_safety: Optional[str] = Field(default=None, description="Sample: Fire compliant; Secure access")
    emergency_preparedness: Optional[str] = Field(default=None, description="Sample: Medical support; Fire drills")
    health_support: Optional[str] = Field(default=None, description="Sample: Health insurance; Mental wellness")
    onboarding_quality: Optional[str] = Field(default=None, description="Sample: Industry-leading")
    learning_culture: Optional[str] = Field(default=None, description="Sample: Internal LMS; Certifications")
    exposure_quality: Optional[str] = Field(default=None, description="Sample: High")
    mentorship_availability: Optional[str] = Field(default=None, description="Sample: Leadership mentors; Peer mentors")
    internal_mobility: Optional[str] = Field(default=None, description="Sample: High")
    promotion_clarity: Optional[str] = Field(default=None, description="Sample: Merit-based; Transparent")
    tools_access: Optional[str] = Field(default=None, description="Sample: Enterprise software; Cloud platforms")
    role_clarity: Optional[str] = Field(default=None, description="Sample: High")
    early_ownership: Optional[str] = Field(default=None, description="Sample: Medium")
    work_impact: Optional[str] = Field(default=None, description="Sample: Client-facing; Revenue-linked")
    execution_thinking_balance: Optional[str] = Field(default=None, description="Sample: Balanced")
    automation_level: Optional[str] = Field(default=None, description="Sample: High")
    cross_functional_exposure: Optional[str] = Field(default=None, description="Sample: Consulting; Technology; Sales")
    company_maturity: Optional[str] = Field(default=None, description="Sample: Mature enterprise")
    brand_value: Optional[str] = Field(default=None, description="Sample: Global top-tier brand")
    client_quality: Optional[str] = Field(default=None, description="Sample: Fortune 500; Governments")
    layoff_history: Optional[str] = Field(default=None, description="Sample: Periodic restructuring")
    fixed_vs_variable_pay: Optional[str] = Field(default=None, description="Sample: Mostly fixed")
    bonus_predictability: Optional[str] = Field(default=None, description="Sample: Moderate")
    esops_incentives: Optional[str] = Field(default=None, description="Sample: Stock grants; Performance shares")
    family_health_insurance: Optional[str] = Field(default=None, description="Sample: Dependents covered; OPD")
    relocation_support: Optional[str] = Field(default=None, description="Sample: Housing; Travel reimbursement")
    lifestyle_benefits: Optional[str] = Field(default=None, description="Sample: Wellness programs; Meals; Fitness")
    exit_opportunities: Optional[str] = Field(default=None, description="Sample: Big Tech; Global consultancies; Industry leadership roles")
    skill_relevance: Optional[str] = Field(default=None, description="Sample: Very High")
    external_recognition: Optional[str] = Field(default=None, description="Sample: Strong global credibility")
    network_strength: Optional[str] = Field(default=None, description="Sample: Global alumni network; Executive connections")
    global_exposure: Optional[str] = Field(default=None, description="Sample: Global clients; International teams")
    mission_clarity: Optional[str] = Field(default=None, description="Sample: High")
    sustainability_csr: Optional[str] = Field(default=None, description="Sample: Net-zero goals; Community programs")
    crisis_behavior: Optional[str] = Field(default=None, description="Sample: Transparent and compliance-driven")
