import re
import json
import pytest
from typing import Dict, Any

# Regex to check if text ends with proper terminal punctuation (including quotes or brackets)
TERMINAL_PUNCTUATION_REGEX = re.compile(r'[.!?)"\u201d\u2019]$')

# List of common truncation placeholders generated by LLMs or parsers when hitting limits
TRUNCATION_PLACEHOLDERS = ["...", "[truncated]", "read more", "etc.", "etc", ".."]


def validate_token_limit_and_truncation(record: Dict[str, Any]) -> bool:
    """
    Evaluates the record holistically to verify that long content has not 
    suffered mid-sentence cutoffs, structural JSON truncation, or trailing parameter drops.
    """
    overview = record.get("Overview of the Company")
    office_locations = record.get("Office Locations")
    ethical_standards = record.get("Ethical standards")  # Schema-end field to verify no drops

    # 1. Validate Narrative Completion (Overview)
    if overview is not None:
        overview_str = str(overview).strip()
        
        # Check for trailing truncation markers
        for placeholder in TRUNCATION_PLACEHOLDERS:
            if overview_str.lower().endswith(placeholder):
                raise ValueError(
                    f"Truncation Detected: 'Overview of the Company' ends with "
                    f"a truncation placeholder '{placeholder}'."
                )
                
        # Check for grammatical completion (must end with terminal punctuation)
        if not TERMINAL_PUNCTUATION_REGEX.search(overview_str):
            raise ValueError(
                f"Grammatical Cutoff Detected: 'Overview of the Company' does not end with "
                f"valid terminal punctuation. Text ends with: '...{overview_str[-20:]}'"
            )

    # 2. Validate Composite Structured Completeness (Office Locations)
    if office_locations is not None:
        locs_str = str(office_locations).strip()
        
        # If expected to be structured JSON, verify it parses cleanly
        if locs_str.startswith("[") or locs_str.startswith("{"):
            try:
                json.loads(locs_str)
            except json.JSONDecodeError as e:
                raise ValueError(
                    f"Structural Truncation Detected: 'Office Locations' failed JSON parsing. "
                    f"It was likely cut off mid-payload. Parsing error: {e}"
                )
        else:
            # For list strings, verify there are no trailing unclosed elements or hanging commas
            if locs_str.endswith(",") or locs_str.endswith("-") or locs_str.endswith("*"):
                raise ValueError(
                    f"Structural Truncation Detected: 'Office Locations' ends with "
                    f"a hanging separator, indicating incomplete list rendering."
                )

    # 3. Validate Schema Preservation (No trailing parameter drops)
    # Under heavy token exhaustion, systems often drop the final keys of a schema
    if not ethical_standards:
         raise ValueError(
             "Schema Preservation Error: Tail-end parameter 'Ethical standards' is missing. "
             "The system may have hit a token ceiling and dropped the end of the schema payload."
         )

    return True


# --- Pytest Suite ---

def test_long_content_perfect_execution_success():
    """
    Validates a highly detailed company profile where narrative and 
    structured fields are highly verbose but structurally complete.
    """
    complete_record = {
        "Overview of the Company": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, and tablets. The firm continues to expand its digital services footprint worldwide.",
        "Office Locations": json.dumps([
            {"city": "Cupertino", "country": "USA"},
            {"city": "London", "country": "UK"},
            {"city": "Tokyo", "country": "Japan"}
        ]),
        "Ethical standards": "Maintains strict supply chain compliance standards globally."
    }
    assert validate_token_limit_and_truncation(complete_record) is True


def test_abrupt_narrative_cutoff_fails():
    """
    Flags a narrative field that gets cut off mid-sentence without terminal punctuation.
    """
    untruncated_but_cutoff_record = {
        "Overview of the Company": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, and",  # Cut off mid-sentence
        "Office Locations": "Cupertino, USA; London, UK",
        "Ethical standards": "Compliant"
    }
    with pytest.raises(ValueError, match="Grammatical Cutoff Detected"):
        validate_token_limit_and_truncation(untruncated_but_cutoff_record)


def test_ellipses_placeholder_fails():
    """
    Flags a narrative field that terminates with a '...' truncation placeholder.
    """
    placeholder_record = {
        "Overview of the Company": "Apple Inc. designs, manufactures, and markets smartphones...",  # Truncated with placeholder
        "Office Locations": "Cupertino, USA",
        "Ethical standards": "Compliant"
    }
    with pytest.raises(ValueError, match="Truncation Detected"):
        validate_token_limit_and_truncation(placeholder_record)


def test_truncated_json_array_fails():
    """
    Flags a structured office location list that is cut off mid-payload, causing JSON parsing to fail.
    """
    truncated_json_record = {
        "Overview of the Company": "Apple Inc. is a consumer tech giant.",
        "Office Locations": '[{"city": "Cupertino", "country": "USA"}, {"city": "London"',  # Cut off JSON array
        "Ethical standards": "Compliant"
    }
    with pytest.raises(ValueError, match="Structural Truncation Detected"):
        validate_token_limit_and_truncation(truncated_json_record)


def test_dropped_tail_end_parameters_fails():
    """
    Flags when final fields in the metadata schema are missing, indicating cumulative token exhaustion.
    """
    exhausted_token_record = {
        "Overview of the Company": "Highly verbose text...",
        "Office Locations": "Cupertino, USA",
        "Ethical standards": None  # Parameter was dropped during extraction
    }
    with pytest.raises(ValueError, match="Schema Preservation Error"):
        validate_token_limit_and_truncation(exhausted_token_record)