import re
import json
import time
from typing import Dict, Any, List, Set, Tuple
import pytest

# =====================================================================
# Constants, Registries, and Regex Patterns
# =====================================================================

# Target Response Time SLAs (in seconds)
SLA_STARTUP_LIMIT_SEC = 15.0
SLA_ENTERPRISE_LIMIT_SEC = 45.0

# Regex to check if text ends with proper terminal punctuation (including quotes or brackets)
TERMINAL_PUNCTUATION_REGEX = re.compile(r'[.!?)"\u201d\u2019]$')

# Common truncation placeholders generated by LLMs or parsers when hitting limits
TRUNCATION_PLACEHOLDERS = ["...", "[truncated]", "read more", "etc.", "etc", ".."]

# Standard dictionary terms and generic English stop words to exclude from signature checks
COMMON_STOP_WORDS = {
    "and", "the", "for", "with", "from", "company", "inc", "corp", "llc", "global", 
    "technologies", "services", "solutions", "limited", "incorporated", "private", 
    "public", "systems", "group", "co", "management", "industries", "partner"
}


# =====================================================================
# Performance Simulation, Truncation, and Context Isolation Functions
# =====================================================================

def simulate_extraction_and_validation(record: Dict[str, Any]) -> Dict[str, Any]:
    """
    Simulates the pipeline extraction, reasoning, and validation of parameters.
    The simulated processing time varies depending on company size, ownership,
    and overall data density.
    """
    # Baseline overhead representing parsing, regex checks, and schema validation
    processing_time = 2.0  
    
    category = record.get("Category", "Startup")
    nature = record.get("Nature of Company", "Private")
    
    # Model higher data density scaling factors
    if category == "Enterprise":
        processing_time += 15.0  # Simulated parsing of dense financial reports
    if nature == "Public":
        processing_time += 10.0  # Simulated query latencies for registries
    if category == "Conglomerate":
        processing_time += 8.0   # Handling complex subsidiaries
        
    # Introduce the simulated processing sleep
    time.sleep(processing_time)
    
    # Return processed record with execution statistics
    record["generation_time_sec"] = processing_time
    record["status"] = "PROCESSED"
    return record


def validate_token_limit_and_truncation(record: Dict[str, Any]) -> bool:
    """
    Evaluates the record to verify that long content has not 
    suffered mid-sentence cutoffs, structural JSON truncation, or trailing parameter drops.
    """
    overview = record.get("Overview of the Company")
    office_locations = record.get("Office Locations")
    ethical_standards = record.get("Ethical standards")  # Schema-end field to verify no drops

    # 1. Validate Narrative Completion (Overview)
    if overview is not None:
        overview_str = str(overview).strip()
        
        # Check for trailing truncation markers
        for placeholder in TRUNCATION_PLACEHOLDERS:
            if overview_str.lower().endswith(placeholder):
                raise ValueError(
                    f"Truncation Detected: 'Overview of the Company' ends with "
                    f"a truncation placeholder '{placeholder}'."
                )
                
        # Check for grammatical completion (must end with terminal punctuation)
        if not TERMINAL_PUNCTUATION_REGEX.search(overview_str):
            raise ValueError(
                f"Grammatical Cutoff Detected: 'Overview of the Company' does not end with "
                f"valid terminal punctuation. Text ends with: '...{overview_str[-20:]}'"
            )

    # 2. Validate Composite Structured Completeness (Office Locations)
    if office_locations is not None:
        locs_str = str(office_locations).strip()
        
        # If expected to be structured JSON, verify it parses cleanly
        if locs_str.startswith("[") or locs_str.startswith("{"):
            try:
                json.loads(locs_str)
            except json.JSONDecodeError as e:
                raise ValueError(
                    f"Structural Truncation Detected: 'Office Locations' failed JSON parsing. "
                    f"It was likely cut off mid-payload. Parsing error: {e}"
                )
        else:
            # For list strings, verify there are no trailing unclosed elements or hanging commas
            if locs_str.endswith(",") or locs_str.endswith("-") or locs_str.endswith("*"):
                raise ValueError(
                    f"Structural Truncation Detected: 'Office Locations' ends with "
                    f"a hanging separator, indicating incomplete list rendering."
                )

    # 3. Validate Schema Preservation (No trailing parameter drops)
    if not ethical_standards:
         raise ValueError(
             "Schema Preservation Error: Tail-end parameter 'Ethical standards' is missing. "
             "The system may have hit a token ceiling and dropped the end of the schema payload."
         )

    return True


def extract_unique_signatures(record: Dict[str, Any]) -> Set[str]:
    """
    Extracts highly specific, lowercase alphanumeric word tokens from a record.
    These tokens serve as the 'data footprint' of the company to detect context leaks.
    """
    signatures: Set[str] = set()
    
    # Target fields that hold highly entity-specific data
    target_fields = [
        "Company Name", "Short Name", "Website URL", "CEO Name", 
        "Company Headquarters", "Key Investors / Backers"
    ]
    
    for field in target_fields:
        val = record.get(field)
        if val:
            # Tokenize and clean the text values
            words = re.findall(r"\b[a-zA-Z]{3,20}\b", str(val).lower())
            for word in words:
                if word not in COMMON_STOP_WORDS:
                    signatures.add(word)
                    
    return signatures


def detect_memory_contamination(company_a: Dict[str, Any], company_b: Dict[str, Any]) -> None:
    """
    Asserts that no highly unique signature tokens from Company A's profile 
    exist in Company B's profile, validating context isolation.
    """
    signatures_a = extract_unique_signatures(company_a)
    
    # Concatenate all values of Company B to search for leakages
    all_b_text = " ".join([str(v) for v in company_b.values() if v is not None]).lower()
    
    # Check for leaks
    leaked_tokens = []
    for token in signatures_a:
        # Enforce boundary checking so standard substrings aren't flagged as leaks
        pattern = re.compile(rf"\b{token}\b")
        if pattern.search(all_b_text):
            leaked_tokens.append(token)
            
    if leaked_tokens:
        raise ValueError(
            f"Memory Contamination Leak Detected: Unique tokens {leaked_tokens} from "
            f"'{company_a.get('Company Name')}' leaked into the record of "
            f"'{company_b.get('Company Name')}'."
        )


# =====================================================================
# Performance, Truncation, and Context Isolation Pytest Suite
# =====================================================================

# --- Performance Suite (tc_13.2.py) ---

def test_startup_generation_response_time():
    """
    Validates that a typical private startup profile with sparse public data 
    is compiled and validated within the fast SLA threshold of 15 seconds.
    """
    startup_payload = {
        "Company Name": "Acme SaaS",
        "Category": "Startup",
        "Nature of Company": "Private"
    }
    
    start_time = time.perf_counter()
    result = simulate_extraction_and_validation(startup_payload)
    end_time = time.perf_counter()
    
    elapsed_time = end_time - start_time
    
    assert elapsed_time <= SLA_STARTUP_LIMIT_SEC, (
        f"Performance SLA Violated: Startup processing took {elapsed_time:.2f}s, "
        f"exceeding the limit of {SLA_STARTUP_LIMIT_SEC}s."
    )
    assert result["status"] == "PROCESSED"


def test_fortune_500_enterprise_generation_response_time():
    """
    Validates that a complex, public Fortune 500 company profile with dense 
    disclosures is compiled and validated within the maximum SLA threshold of 45 seconds.
    """
    enterprise_payload = {
        "Company Name": "Microsoft Corporation",
        "Category": "Enterprise",
        "Nature of Company": "Public"
    }
    
    start_time = time.perf_counter()
    result = simulate_extraction_and_validation(enterprise_payload)
    end_time = time.perf_counter()
    
    elapsed_time = end_time - start_time
    
    assert elapsed_time <= SLA_ENTERPRISE_LIMIT_SEC, (
        f"Performance SLA Violated: Enterprise processing took {elapsed_time:.2f}s, "
        f"exceeding the limit of {SLA_ENTERPRISE_LIMIT_SEC}s."
    )
    assert result["status"] == "PROCESSED"


def test_public_vs_private_latency_scaling():
    """
    Compares processing speed differences between public and private company profiles.
    Asserts that the system scales with proportional processing speeds relative to data density.
    """
    private_payload = {
        "Company Name": "Alpha Robotics",
        "Category": "Startup",
        "Nature of Company": "Private"
    }
    
    public_payload = {
        "Company Name": "Tesla Inc.",
        "Category": "Enterprise",
        "Nature of Company": "Public"
    }
    
    # Measure Private
    t_start_private = time.perf_counter()
    res_private = simulate_extraction_and_validation(private_payload)
    t_end_private = time.perf_counter()
    private_duration = t_end_private - t_start_private
    
    # Measure Public
    t_start_public = time.perf_counter()
    res_public = simulate_extraction_and_validation(public_payload)
    t_end_public = time.perf_counter()
    public_duration = t_end_public - t_start_public
    
    # Private startup must be faster than public enterprise due to data scale differences
    assert private_duration < public_duration, (
        f"Abnormal Latency Profile: Private startup processing ({private_duration:.2f}s) "
        f"was not faster than public enterprise processing ({public_duration:.2f}s)."
    )
    
    assert private_duration <= SLA_STARTUP_LIMIT_SEC
    assert public_duration <= SLA_ENTERPRISE_LIMIT_SEC


# --- Truncation Suite (tc_13.3.py) ---

def test_long_content_perfect_execution_success():
    """
    Validates a detailed company profile where narrative and 
    structured fields are verbose but structurally complete.
    """
    complete_record = {
        "Overview of the Company": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, and tablets. The firm continues to expand its digital services footprint worldwide.",
        "Office Locations": json.dumps([
            {"city": "Cupertino", "country": "USA"},
            {"city": "London", "country": "UK"},
            {"city": "Tokyo", "country": "Japan"}
        ]),
        "Ethical standards": "Maintains strict supply chain compliance standards globally."
    }
    assert validate_token_limit_and_truncation(complete_record) is True


def test_abrupt_narrative_cutoff_fails():
    """Flags a narrative field that gets cut off mid-sentence without terminal punctuation."""
    untruncated_but_cutoff_record = {
        "Overview of the Company": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, and",
        "Office Locations": "Cupertino, USA; London, UK",
        "Ethical standards": "Compliant"
    }
    with pytest.raises(ValueError, match="Grammatical Cutoff Detected"):
        validate_token_limit_and_truncation(untruncated_but_cutoff_record)


def test_ellipses_placeholder_fails():
    """Flags a narrative field that terminates with a '...' truncation placeholder."""
    placeholder_record = {
        "Overview of the Company": "Apple Inc. designs, manufactures, and markets smartphones...",
        "Office Locations": "Cupertino, USA",
        "Ethical standards": "Compliant"
    }
    with pytest.raises(ValueError, match="Truncation Detected"):
        validate_token_limit_and_truncation(placeholder_record)


def test_truncated_json_array_fails():
    """Flags a structured office location list that is cut off mid-payload, causing JSON parsing to fail."""
    truncated_json_record = {
        "Overview of the Company": "Apple Inc. is a consumer tech giant.",
        "Office Locations": '[{"city": "Cupertino", "country": "USA"}, {"city": "London"',
        "Ethical standards": "Compliant"
    }
    with pytest.raises(ValueError, match="Structural Truncation Detected"):
        validate_token_limit_and_truncation(truncated_json_record)


def test_dropped_tail_end_parameters_fails():
    """Flags when final fields in the metadata schema are missing, indicating cumulative token exhaustion."""
    exhausted_token_record = {
        "Overview of the Company": "Highly verbose text...",
        "Office Locations": "Cupertino, USA",
        "Ethical standards": None
    }
    with pytest.raises(ValueError, match="Schema Preservation Error"):
        validate_token_limit_and_truncation(exhausted_token_record)


# --- Isolation Suite (tc_13.4.py) ---

def test_sequential_requests_perfect_isolation_success():
    """
    Validates that two highly distinct sequential requests preserve 
    context isolation and do not trigger leak detection.
    """
    company_a = {
        "Company Name": "Space Exploration Technologies Corp.",
        "Short Name": "SpaceX",
        "Website URL": "https://www.spacex.com",
        "CEO Name": "Elon Musk",
        "Company Headquarters": "Hawthorne, California",
        "Key Investors / Backers": "Founders Fund, Fidelity"
    }
    
    company_b = {
        "Company Name": "Blue Origin LLC",
        "Short Name": "Blue Origin",
        "Website URL": "https://www.blueorigin.com",
        "CEO Name": "Jeff Bezos",
        "Company Headquarters": "Kent, Washington",
        "Key Investors / Backers": "Bezos Expeditions"
    }
    
    detect_memory_contamination(company_a, company_b)


def test_sequential_requests_contamination_failure():
    """
    Asserts that the memory leak detector successfully catches and flags 
    cross-contamination if a preceding company's attributes bleed into the next record.
    """
    company_a = {
        "Company Name": "Space Exploration Technologies Corp.",
        "Short Name": "SpaceX",
        "Website URL": "https://www.spacex.com",
        "CEO Name": "Elon Musk",
        "Company Headquarters": "Hawthorne, California",
        "Key Investors / Backers": "Founders Fund, Fidelity"
    }
    
    contaminated_company_b = {
        "Company Name": "Blue Origin LLC",
        "Short Name": "Blue Origin",
        "Website URL": "https://www.spacex.com",  # Leaked domain
        "CEO Name": "Elon Musk",                 # Leaked CEO
        "Company Headquarters": "Kent, Washington",
        "Key Investors / Backers": "Bezos Expeditions"
    }
    
    with pytest.raises(ValueError, match="Memory Contamination Leak Detected"):
        detect_memory_contamination(company_a, contaminated_company_b)


def test_batch_run_similar_companies_isolation():
    """
    Checks that highly similar automotive entities parsed concurrently 
    do not experience cross-contamination of their specific identifiers.
    """
    tesla = {
        "Company Name": "Tesla Inc.",
        "Short Name": "Tesla",
        "Website URL": "https://www.tesla.com",
        "CEO Name": "Elon Musk",
        "Company Headquarters": "Austin, Texas"
    }
    
    rivian = {
        "Company Name": "Rivian Automotive",
        "Short Name": "Rivian",
        "Website URL": "https://www.rivian.com",
        "CEO Name": "RJ Scaringe",
        "Company Headquarters": "Irvine, California"
    }
    
    detect_memory_contamination(tesla, rivian)
    detect_memory_contamination(rivian, tesla)